dropit: bail out if pkg-prune.rkt is not found

diff --git a/dropit/dropit b/dropit/dropit
--- a/dropit/dropit
+++ b/dropit/dropit
@@ -264,6 +264,9 @@ if [[ -n "$usePkgPrune" ]]; then
     declare pkgPrunePath
     pkgPrunePath="$(dirname "$(realpath "$0")")/../pkg-prune.rkt"
     command -v racket &>/dev/null || die "racket is not installed"
+    if ! [[ -f "$pkgPrunePath" ]]; then
+        die "pkg-prune.rkt is not found at $pkgPrunePath"
+    fi
     log "[*] Found pkg-prune.rkt: $pkgPrunePath"
 fi
 
